services:
  backend:
    build:
      context: ./
      # context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./
      # context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-data: