version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/stream

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
